# Generated by Django 5.2.12 on 2026-04-04 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cellars", "0002_bottle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bottle",
            name="name",
        ),
    ]
