# Generated by Django 5.2.12 on 2026-04-06 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cellars", "0003_remove_bottle_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cellar",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_cellar_name_per_user"
            ),
        ),
    ]
