# Generated by Django 5.2.12 on 2026-04-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
